version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    expose:
      - "5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
