version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - 5000
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: always
