version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
